name: "Publish dotnet lib"
description: "Deploy dotnet lib to registry"

inputs:
  path:
    description: "Path of the project"
    required: true
  nupkg_path:
    description: "Path of the nupkg"
    required: true
  source:
    description: "Destination package source"
    required: true
  api_key:
    description: "Destination package source api key"
    required: true

runs:
  using: "composite"
  steps:

    - name: Build the Library
      shell: "bash"
      run: |
          cd ${{ inputs.path }}
          dotnet build --configuration Release

    - name: Create nuget packages
      shell: "bash"
      run: dotnet pack ${{ inputs.path }} --configuration Release --no-build

    - name: Add github as a source
      shell: "bash"
      run: dotnet nuget add source --username onurkanbakirci --password ${{inputs.api_key}} --name github https://nuget.pkg.github.com/onurkanbakirci/index.json

    - name: Publish nuget packages
      shell: "bash"
      run: dotnet nuget push ${{ inputs.nupkg_path }} --source ${{inputs.source}} --api-key ${{inputs.api_key}}