name: Integration.Marketplaces.Hepsiburada

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

    paths:
      - src/Integration.Hub/**
      - src/Marketplaces/Integration.Marketplaces.Hepsiburada/**
      - .github/workflows/hepsiburada-integration.yml
      - .github/workflows/composite/**

env:
  #For build process
  owner: onurkanbakirci
  repo: Integration

  project_path: ./src/Marketplaces/Integration.Marketplaces.Hepsiburada/
  nupkg_path: ./src/Marketplaces/Integration.Marketplaces.Hepsiburada/bin/Release/Integration.Marketplaces.Hepsiburada.1.0.1.nupkg
  nupkg_github_secret: ${{ secrets.GITHUB_TOKEN }}
  nupkg_nuget_secret: ${{ secrets.NUGET_API_KEY }}
  github_registry_url: https://nuget.pkg.github.com/onurkanbakirci/index.json
  nuget_registry_url: https://api.nuget.org/v3/index.json

jobs:
  build_lib:
    name: Build Lib
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          cd ${{env.project_path}}
          dotnet build --no-restore

  test_lib:
    name: Test Lib
    runs-on: ubuntu-latest
    needs: build_lib

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        run: |

  publish_lib_to_github:
    name: Publish Lib to Github
    runs-on: ubuntu-latest
    needs: test_lib
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push nuget package to github registry
        uses: ./.github/workflows/composite/publish-lib
        with:
          package_source: ${{ env.github_registry_url }}
          path: ${{ env.project_path }}
          nupkg_path: ${{ env.nupkg_path }}
          api_key: ${{ env.nupkg_github_secret }}

  publish_lib_to_nuget:
    name: Publish Lib to Nuget
    runs-on: ubuntu-latest
    needs: test_lib
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push nuget package to nuget registry
        uses: ./.github/workflows/composite/publish-lib
        with:
          package_source: ${{ env.nuget_registry_url }}
          path: ${{ env.project_path }}
          nupkg_path: ${{ env.nupkg_path }}
          api_key: ${{ env.nupkg_nuget_secret }}
