name: Integration.Core

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

    paths:
      - src/Integration.Core/**
      - .github/workflows/integration-core.yml
      - .github/workflows/composite/**

env:
  #For build process
  owner: onurkanbakirci
  repo: Integration

  project_path: ./src/Integration.Core/
  nupkg_path: ./src/Integration.Core/bin/Release/net8.0/Integration.Core.12.12.23.1.0.0.nupkg
  nupkg_source: 'github'
  nupkg_secret: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-lib:
    name: Build Lib
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          cd ${{env.project_path}}
          dotnet build --no-restore

  test-lib:
    name: Test Lib
    runs-on: ubuntu-latest
    needs: build-lib

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        run: |

  publish-lib:
    name: Publish Lib
    runs-on: ubuntu-latest
    needs: test-lib
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: ./.github/workflows/composite/publish-lib
        with:
          path: ${{ env.project_path }}
          nupkg_path: ${{env.nupkg_path}}
          source: ${{ env.nupkg_source }}
          api_key: ${{ env.nupkg_secret }}